const COUNT_ACTION = {
  INCREMENT_REQUEST: 'INCREMENT_REQUEST',
  INCREMENT: 'INCREMENT',
  INCREMENT_ASYNC: 'INCREMENT_ASYNC',

  DECREMENT_REQUEST: 'DECREMENT_REQUEST',
  DECREMENT: 'DECREMENT',
  DECREMENT_ASYNC: 'DECREMENT_ASYNC',
}

export default COUNT_ACTION
